#!/usr/bin/env ruby

require 'erb'

REPO_DIR = ENV['OPENSHIFT_REPO_DIR']
renderer = ERB.new(File.join(REPO_DIR, 'conf.d', File.read('httpd-proxy.conf.erb')))
File.write( File.join(REPO_DIR, 'conf.d', 'httpd-proxy.conf'), renderer.result )
